name: build

on:
  push:
    tags:
      - v*
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    # https://github.com/golangci/golangci-lint-action
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.50.1

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0
        args: --config=.golangci.yml

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: false

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@main

    - name: Build
      run: go build -v ./cmd/gorcon

  docker-release:
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: outdead
          password: ${{ secrets.GORCON_DOCKER_TOKEN }}
      
      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/docker/Dockerfile
          push: true
          build-args: |
            VERSION=0.0.0-develop
          tags: |
            outdead/rcon:latest
